"use client";

import { Check, ChevronLeft, ChevronRight, Copy, Plus, ReceiptText, TrendingDown, TrendingUp, Upload } from "lucide-react";
import { useMemo, useRef, useState } from "react";
import { BubbleHeader, Card, MetricCard } from "@/components/ui/card";
import { Field, Sheet } from "@/components/ui/modal";
import { RowMenu } from "@/components/ui/menu";
import { useBudgyData } from "@/lib/data/data-provider";
import { budgetSummary, displayPotential, entriesForMonth } from "@/lib/domain/budget";
import { eur, fromDateInput, monthLabel, shortDate, toDateInput } from "@/lib/format";
import type { BudgetEntry, EntryType } from "@/types/domain";

type Draft = Pick<BudgetEntry,"title"|"amount"|"potentialAmount"|"type"|"category"|"bucket"|"scope"|"date"|"note"|"status">;
const blankDraft = (date:Date):Draft=>({title:"",amount:0,potentialAmount:0,type:"depense",category:"Autre",bucket:"Variable",scope:"Perso",date:date.toISOString(),note:"",status:"non"});

export default function BudgetPage(){
  const {data,ready,create,update,remove}=useBudgyData(); const [selectedMonth,setSelectedMonth]=useState(()=>new Date()); const [open,setOpen]=useState(false); const [editing,setEditing]=useState<string>(); const [draft,setDraft]=useState<Draft>(()=>blankDraft(new Date())); const [notice,setNotice]=useState(""); const fileRef=useRef<HTMLInputElement>(null);
  const entries=useMemo(()=>entriesForMonth(data.budgetEntries,selectedMonth),[data.budgetEntries,selectedMonth]); const summary=useMemo(()=>budgetSummary(entries),[entries]);
  const sections=[{title:"Rentrées",items:entries.filter((x)=>x.type==="revenu")},{title:"Charges",items:entries.filter((x)=>x.type==="depense"&&x.bucket.toLowerCase().includes("charge"))},{title:"Dépenses",items:entries.filter((x)=>x.type==="depense"&&!x.bucket.toLowerCase().includes("charge"))}];
  const showCreate=()=>{setEditing(undefined);setDraft(blankDraft(new Date(selectedMonth.getFullYear(),selectedMonth.getMonth(),Math.min(new Date().getDate(),28),12)));setOpen(true);};
  const showEdit=(entry:BudgetEntry)=>{setEditing(entry.id);setDraft({...entry});setOpen(true);};
  const save=()=>{if(!draft.title.trim()||draft.amount<=0)return; if(editing)update("budgetEntries",editing,draft);else create("budgetEntries",draft);setOpen(false);};
  const moveMonth=(offset:number)=>setSelectedMonth((value)=>new Date(value.getFullYear(),value.getMonth()+offset,1));
  const copyNext=()=>{const target=new Date(selectedMonth.getFullYear(),selectedMonth.getMonth()+1,1);let count=0;for(const entry of entries){const source=new Date(entry.date);const lastDay=new Date(target.getFullYear(),target.getMonth()+1,0).getDate();const day=Math.min(source.getDate(),lastDay);const duplicate=data.budgetEntries.some((candidate)=>{const date=new Date(candidate.date);return date.getFullYear()===target.getFullYear()&&date.getMonth()===target.getMonth()&&date.getDate()===day&&candidate.title.trim().toLowerCase()===entry.title.trim().toLowerCase()&&candidate.amount===entry.amount&&candidate.type===entry.type&&candidate.category===entry.category&&candidate.bucket===entry.bucket;});if(!duplicate){create("budgetEntries",{title:entry.title,amount:entry.amount,potentialAmount:entry.potentialAmount,type:entry.type,category:entry.category,bucket:entry.bucket,scope:entry.scope,note:entry.note,status:"non",date:new Date(target.getFullYear(),target.getMonth(),day,12).toISOString()});count++;}}setNotice(`${count} élément${count>1?"s":""} copié${count>1?"s":""}`);setTimeout(()=>setNotice(""),3000);};
  const importCsv=async(file:File)=>{const text=await file.text();const lines=text.split(/\r?\n/).filter(Boolean);const headers=(lines.shift()??"").split(",").map((x)=>x.trim().toLowerCase());let count=0;for(const line of lines){const values=line.split(",");const value=(...names:string[])=>{const index=headers.findIndex((header)=>names.includes(header));return index>=0?(values[index]??"").trim():"";};const amount=Math.abs(Number(value("montant","amount").replace(",",".")));const title=value("description","libellé","libelle")||"Import Revolut";if(amount>0){create("budgetEntries",{...blankDraft(selectedMonth),title,amount,type:Number(value("montant","amount").replace(",","."))>=0?"revenu":"depense",category:"Import Revolut",date:value("date","datedefin")?new Date(value("date","datedefin")).toISOString():selectedMonth.toISOString()});count++;}}setNotice(`${count} transaction${count>1?"s":""} importée${count>1?"s":""}`);};
  if(!ready)return <main className="page stack"><div className="skeleton" style={{height:150}}/><div className="skeleton"/></main>;
  return <main className="page page-narrow stack"><BubbleHeader title="Budget" subtitle="Réalisé, potentiel et prévisions" action={<button className="fab" aria-label="Nouvelle transaction" onClick={showCreate}><Plus/></button>}/>
    <Card><div className="spread"><button className="icon-button" onClick={()=>moveMonth(-1)} aria-label="Mois précédent"><ChevronLeft/></button><strong>{monthLabel(selectedMonth)}</strong><button className="icon-button" onClick={()=>moveMonth(1)} aria-label="Mois suivant"><ChevronRight/></button></div><button className="button button-soft" style={{width:"100%",marginTop:12}} onClick={copyNext}><Copy size={17}/> Copier vers mois suivant</button>{notice&&<p className="positive small" style={{textAlign:"center",marginBottom:0}}>{notice}</p>}</Card>
    <div className="grid-2"><MetricCard icon={TrendingUp} label="Solde réalisé" value={eur.format(summary.confirmedBalance)} detail={`Reçus ${eur.format(summary.confirmedIncome)}`} tone={summary.confirmedBalance>=0?"green":"orange"}/><MetricCard icon={TrendingDown} label="Solde potentiel" value={eur.format(summary.projectedBalance)} detail={`À venir ${eur.format(summary.pendingIncome-summary.pendingExpenses)}`} tone="purple"/></div>
    <Card><div className="grid-2"><div><span className="muted small">Dépenses réalisées</span><strong className="amount negative" style={{display:"block",marginTop:5}}>{eur.format(summary.confirmedExpenses)}</strong></div><div><span className="muted small">Dépenses potentielles</span><strong className="amount orange" style={{display:"block",marginTop:5}}>{eur.format(summary.pendingExpenses)}</strong></div></div></Card>
    {sections.map((section)=><Card key={section.title}><div className="spread"><h2 className="section-title">{section.title}</h2><span className="amount">{eur.format(section.items.reduce((sum,item)=>sum+(item.status==="recu"?item.amount:displayPotential(item)),0))}</span></div>{section.items.length===0?<p className="muted small">Aucun élément ce mois.</p>:section.items.map((entry)=><div className="list-row" key={entry.id} onClick={()=>showEdit(entry)}><button className={`status-dot ${entry.status==="recu"?"active":""}`} aria-label={entry.status==="recu"?"Passer en attente":"Confirmer"} onClick={(event)=>{event.stopPropagation();update("budgetEntries",entry.id,{status:entry.status==="recu"?"non":"recu"});}}>{entry.status==="recu"&&<Check size={15}/>}</button><div className="list-main"><strong>{entry.title}</strong><span className="muted small">{entry.category} · {shortDate(entry.date)} · {entry.status==="recu"?"Réalisé":"En attente"}</span></div><strong className={entry.type==="revenu"?"positive":"negative"}>{entry.type==="revenu"?"+":"−"}{eur.format(entry.status==="recu"?entry.amount:displayPotential(entry))}</strong><RowMenu onEdit={()=>showEdit(entry)} onDelete={()=>remove("budgetEntries",entry.id)}/></div>)}</Card>)}
    <Card><div className="spread"><div className="row"><span className="icon-tile icon-purple"><ReceiptText size={19}/></span><div><strong>Import Revolut</strong><div className="muted small">CSV description, montant, date</div></div></div><button className="button button-soft" onClick={()=>fileRef.current?.click()}><Upload size={17}/>Importer</button></div><input ref={fileRef} type="file" accept=".csv,text/csv" hidden onChange={(event)=>{const file=event.target.files?.[0];if(file)void importCsv(file);}}/></Card>
    <Sheet open={open} title={editing?"Modifier transaction":"Nouvelle transaction"} submitLabel={editing?"Enregistrer":"Ajouter"} disableSubmit={!draft.title.trim()||draft.amount<=0} onClose={()=>setOpen(false)} onSubmit={save}><div className="form-grid"><Field label="Intitulé"><input className="input" value={draft.title} placeholder="Intitulé de la transaction…" onChange={(event)=>setDraft({...draft,title:event.target.value})}/></Field><Field label="Montant"><input className="input" type="number" inputMode="decimal" min="0" value={draft.amount||""} placeholder="0,00" onChange={(event)=>setDraft({...draft,amount:Number(event.target.value)})}/></Field><Field label="Type"><div className="segmented">{(["revenu","depense"] as EntryType[]).map((type)=><button key={type} className={draft.type===type?"active":""} onClick={()=>setDraft({...draft,type,bucket:type==="revenu"?"Rentrée":"Variable"})}>{type==="revenu"?"Revenu":"Dépense"}</button>)}</div></Field><Field label="Catégorie"><input className="input" value={draft.category} onChange={(event)=>setDraft({...draft,category:event.target.value})}/></Field><div className="grid-2"><Field label="Groupe"><select className="select" value={draft.bucket} onChange={(event)=>setDraft({...draft,bucket:event.target.value})}><option>Rentrée</option><option>Charge fixe</option><option>Variable</option><option>Voyage</option></select></Field><Field label="Scope"><input className="input" value={draft.scope} onChange={(event)=>setDraft({...draft,scope:event.target.value})}/></Field></div><Field label="Date"><input className="input" type="date" value={toDateInput(draft.date)} onChange={(event)=>setDraft({...draft,date:fromDateInput(event.target.value)})}/></Field><Field label="Commentaire"><textarea className="textarea" value={draft.note} placeholder="Commentaire optionnel…" onChange={(event)=>setDraft({...draft,note:event.target.value})}/></Field>{editing&&<button className="button button-danger" onClick={()=>{remove("budgetEntries",editing);setOpen(false);}}>Supprimer la transaction</button>}</div></Sheet>
  </main>;
}
