"use client";
import { ArrowDownCircle,ArrowLeft,ArrowUpCircle,Banknote,Check,PackageCheck,PackageOpen,Paperclip,Percent,Plus,ReceiptText,ShoppingCart,Tag } from "lucide-react";
import { useEffect,useMemo,useRef,useState } from "react";
import Link from "next/link";
import { AttachmentManager } from "@/components/attachment-manager";
import { ConfirmDialog,useToast } from "@/components/ui/feedback";
import { RowMenu } from "@/components/ui/menu";
import { Field,Sheet } from "@/components/ui/modal";
import { AmountField,AnimatedSegmented,FormSection } from "@/components/ui/premium";
import { useBudgyData } from "@/lib/data/data-provider";
import { convertCurrency,dubaiCashSummary,partMetrics } from "@/lib/domain/dubai";
import { money,shortDate } from "@/lib/format";
import type { Currency,DubaiCashMovement,DubaiPart } from "@/types/domain";

type PartDraft=Pick<DubaiPart,"name"|"category"|"quantityBought"|"quantitySold"|"purchasePriceAED"|"targetSalePriceAED"|"note"|"cashWithdrawnAED">;
type Action="sale"|"expense"|"movement";
const blankPart:PartDraft={name:"",category:"Pièces auto",quantityBought:0,quantitySold:0,purchasePriceAED:0,targetSalePriceAED:0,note:"",cashWithdrawnAED:0};

export default function DubaiPage(){
 const {data,create,update,remove}=useBudgyData();
 const [currency,setCurrency]=useState<Currency>(()=>(typeof window!=="undefined"?(localStorage.getItem("budgy.dubai.currency") as Currency):"AED")||"AED");
 const [partOpen,setPartOpen]=useState(false),[editingPart,setEditingPart]=useState<string>(),[documentPart,setDocumentPart]=useState<string>();
 const [partDraft,setPartDraft]=useState<PartDraft>(blankPart),[action,setAction]=useState<Action>(),[selectedPart,setSelectedPart]=useState("");
 const [title,setTitle]=useState(""),[amount,setAmount]=useState(0),[quantity,setQuantity]=useState(1),[actionCurrency,setActionCurrency]=useState<Currency>("AED");
 const [movementType,setMovementType]=useState<DubaiCashMovement["type"]>("cash_out"),[planned,setPlanned]=useState(false);
 const [pendingDelete,setPendingDelete]=useState<{kind:"part"|"movement";id:string;label:string}>();
 const actionHandled=useRef(false);const {showToast}=useToast();
 const cash=useMemo(()=>dubaiCashSummary(data.dubaiSales,data.dubaiExpenses,data.dubaiCashMovements,currency),[currency,data.dubaiCashMovements,data.dubaiExpenses,data.dubaiSales]);
 const allMetrics=data.dubaiParts.map((part)=>partMetrics(part,data.dubaiSales,data.dubaiExpenses));
 const bought=allMetrics.reduce((sum,item)=>sum+item.totalBoughtAED,0),potential=allMetrics.reduce((sum,item)=>sum+item.totalPotentialRevenueAED,0);
 const remaining=data.dubaiParts.reduce((sum,part,index)=>sum+(allMetrics[index]?.realRemainingQuantity??part.quantityBought),0),sold=data.dubaiParts.reduce((sum,part,index)=>sum+(allMetrics[index]?.realQuantitySoldFromSales??part.quantitySold),0),totalQty=data.dubaiParts.reduce((sum,item)=>sum+item.quantityBought,0);
 const display=(aed:number)=>money(convertCurrency(aed,"AED",currency),currency);
 const chooseCurrency=(value:Currency)=>{setCurrency(value);localStorage.setItem("budgy.dubai.currency",value);};
 const editPart=(part:DubaiPart)=>{setEditingPart(part.id);setPartDraft({name:part.name,category:part.category,quantityBought:part.quantityBought,quantitySold:part.quantitySold,purchasePriceAED:part.purchasePriceAED,targetSalePriceAED:part.targetSalePriceAED,note:part.note,cashWithdrawnAED:part.cashWithdrawnAED});setPartOpen(true);};
 const savePart=()=>{if(!partDraft.name.trim()||partDraft.quantityBought<0)return;if(editingPart)update("dubaiParts",editingPart,partDraft);else create("dubaiParts",{...partDraft,createdAt:new Date().toISOString()});showToast({title:editingPart?"Référence modifiée":"Référence ajoutée",tone:"success"});setPartOpen(false);};
 const openAction=(kind:Action,partId="")=>{setAction(kind);setSelectedPart(partId);setTitle("");setAmount(0);setQuantity(1);setActionCurrency("AED");setMovementType("cash_out");setPlanned(false);};
 const saveAction=()=>{if(!action||amount<=0)return;if(action==="sale"&&selectedPart)create("dubaiSales",{partId:selectedPart,quantity,unitSalePriceAED:amount,currency:actionCurrency,date:new Date().toISOString(),customerName:title||"Client",note:""});else if(action==="expense")create("dubaiExpenses",{partId:selectedPart||undefined,title:title||"Charge",amountAED:amount,currency:actionCurrency,date:new Date().toISOString(),category:"Autre",note:""});else if(action==="movement")create("dubaiCashMovements",{title:title||"Mouvement",amount,currency:actionCurrency,date:new Date().toISOString(),type:movementType,category:movementType==="withdrawal"?"Retrait":"Cash",note:"",status:planned?"planned":"done"});else return;showToast({title:action==="sale"?"Vente ajoutée":action==="expense"?"Charge ajoutée":"Mouvement enregistré",tone:"success"});setAction(undefined);};

 useEffect(()=>{if(actionHandled.current)return;const timer=window.setTimeout(()=>{actionHandled.current=true;const requested=new URLSearchParams(window.location.search).get("action");if(requested==="sale"||requested==="expense"||requested==="movement")openAction(requested);},0);return()=>window.clearTimeout(timer);},[]);

 return <main className="page dubai-page"><header className="business-subnav"><Link href="/business"><ArrowLeft size={17}/> Business</Link><strong>Dubaï</strong><button className="compact-add" onClick={()=>{setEditingPart(undefined);setPartDraft(blankPart);setPartOpen(true);}}><Plus size={18}/> Référence</button></header>
  <AnimatedSegmented value={currency} options={(["AED","EUR","FCFA","USD"] as Currency[]).map((value)=>({value,label:value}))} onChange={chooseCurrency} label="Devise d’affichage"/>
  <section className="dubai-kpis"><article><span><Tag size={16}/></span><strong>{data.dubaiParts.length}</strong><small>Références</small></article><article><span><PackageOpen size={16}/></span><strong>{remaining}</strong><small>En stock</small></article><article><span><ShoppingCart size={16}/></span><strong>{sold}/{totalQty}</strong><small>Vendus</small></article><article><span><Percent size={16}/></span><strong>{totalQty?Math.round(sold/totalQty*100):0} %</strong><small>Taux de vente</small></article></section>
  <section className="dubai-finance"><header><div><span>Résultat actuel</span><strong className={cash.currentResult>=0?"positive":"negative"}>{money(cash.currentResult,currency)}</strong></div><Banknote size={28}/></header><div><span>Investi<strong>{display(bought)}</strong></span><span>Potentiel<strong>{display(potential)}</strong></span><span>Encaissé<strong>{money(cash.salesTotal,currency)}</strong></span><span>Décaissé<strong>{money(cash.totalDisbursed,currency)}</strong></span></div></section>
  <section className="dubai-actions"><button onClick={()=>openAction("sale")}><PackageCheck size={17}/>Vente</button><button onClick={()=>openAction("expense")}><ReceiptText size={17}/>Charge</button><button onClick={()=>openAction("movement")}><Banknote size={17}/>Mouvement cash</button></section>
  <section className="dense-list-card"><header><h2>Stock</h2><span>{remaining} unités restantes</span></header>{data.dubaiParts.map((part)=>{const metric=partMetrics(part,data.dubaiSales,data.dubaiExpenses);const progress=part.quantityBought?Math.min(metric.realQuantitySoldFromSales/part.quantityBought*100,100):0;return <article className="stock-row" key={part.id}><div className="stock-row-head"><span><strong>{part.name}</strong><small>{part.category}</small></span><span><strong>{metric.realRemainingQuantity} restant{metric.realRemainingQuantity>1?"s":""}</strong><small>{display(metric.projectedRemainingRevenueAED)} potentiel</small></span></div><div className="stock-track"><i style={{width:`${progress}%`}}/></div><div className="stock-numbers"><span>Achat<strong>{display(part.purchasePriceAED)}</strong></span><span>Vendu<strong>{metric.realQuantitySoldFromSales}/{part.quantityBought}</strong></span><span>Cible<strong>{display(part.targetSalePriceAED)}</strong></span></div><div className="stock-actions"><button className="icon-button" aria-label={`Documents ${part.name}`} onClick={()=>setDocumentPart(part.id)}><Paperclip size={16}/></button><button className="button button-soft" onClick={()=>openAction("sale",part.id)}>Vente</button><RowMenu onEdit={()=>editPart(part)} onDelete={()=>setPendingDelete({kind:"part",id:part.id,label:part.name})}/></div></article>;})}</section>
  <section className="dense-list-card"><header><h2>Cash</h2><button className="compact-link" onClick={()=>openAction("movement")}><Plus size={15}/>Ajouter</button></header>{data.dubaiCashMovements.length?data.dubaiCashMovements.map((movement)=><div className="cash-row" key={movement.id}><span className={`cash-icon ${movement.type==="cash_in"?"cash-in":"cash-out"}`}>{movement.type==="cash_in"?<ArrowDownCircle/>:<ArrowUpCircle/>}</span><span className="list-main"><strong>{movement.title}</strong><small>{movement.status==="planned"?"Prévu":"Réalisé"} · {shortDate(movement.date)}</small></span><strong className={movement.type==="cash_in"?"positive":"negative"}>{money(movement.amount,movement.currency)}</strong><RowMenu onEdit={()=>{setAction("movement");setTitle(movement.title);setAmount(movement.amount);setActionCurrency(movement.currency);setMovementType(movement.type);setPlanned(movement.status==="planned");}} onDelete={()=>setPendingDelete({kind:"movement",id:movement.id,label:movement.title})}/></div>):<p className="dense-empty">Aucun mouvement enregistré.</p>}</section>

  <Sheet open={Boolean(documentPart)} title="Documents de la référence" onClose={()=>setDocumentPart(undefined)}>{documentPart?<AttachmentManager dubaiPartId={documentPart}/>:null}</Sheet>
  <Sheet open={partOpen} title={editingPart?"Modifier la référence":"Ajouter une référence"} submitLabel={editingPart?"Enregistrer":"Ajouter"} disableSubmit={!partDraft.name.trim()} onClose={()=>setPartOpen(false)} onSubmit={savePart} icon={Tag} tone="orange"><div className="form-grid"><FormSection title="Référence"><Field label="Nom"><input className="input" autoCapitalize="words" value={partDraft.name} onChange={(event)=>setPartDraft({...partDraft,name:event.target.value})}/></Field><Field label="Catégorie"><input className="input" value={partDraft.category} onChange={(event)=>setPartDraft({...partDraft,category:event.target.value})}/></Field></FormSection><FormSection title="Stock et prix"><div className="grid-2"><Field label="Quantité achetée"><input className="input" type="number" inputMode="numeric" value={partDraft.quantityBought||""} onChange={(event)=>setPartDraft({...partDraft,quantityBought:Number(event.target.value)})}/></Field><Field label="Vendue manuelle"><input className="input" type="number" inputMode="numeric" value={partDraft.quantitySold||""} onChange={(event)=>setPartDraft({...partDraft,quantitySold:Number(event.target.value)})}/></Field></div><div className="grid-2"><Field label="Achat AED"><AmountField size="compact" suffix="AED" value={partDraft.purchasePriceAED} onChange={(v)=>setPartDraft({...partDraft,purchasePriceAED:v})}/></Field><Field label="Vente cible AED"><AmountField size="compact" suffix="AED" value={partDraft.targetSalePriceAED} onChange={(v)=>setPartDraft({...partDraft,targetSalePriceAED:v})}/></Field></div></FormSection><Field label="Note"><textarea className="textarea" value={partDraft.note} onChange={(event)=>setPartDraft({...partDraft,note:event.target.value})}/></Field></div></Sheet>
  <Sheet open={Boolean(action)} title={action==="sale"?"Enregistrer une vente":action==="expense"?"Ajouter une charge":"Mouvement d’argent"} submitLabel="Enregistrer" disableSubmit={amount<=0||(action==="sale"&&!selectedPart)} onClose={()=>setAction(undefined)} onSubmit={saveAction} icon={action==="sale"?PackageCheck:action==="expense"?ReceiptText:Banknote} tone={action==="sale"?"green":"orange"}><div className="transaction-form"><Field label={action==="sale"?"Prix unitaire":"Montant"}><AmountField value={amount} onChange={setAmount} suffix={actionCurrency} autoFocus /></Field><FormSection title="Détails"><Field label={action==="sale"?"Client":"Intitulé"}><input className="input" value={title} onChange={(event)=>setTitle(event.target.value)}/></Field>{action==="sale"?<><Field label="Référence"><select className="select" value={selectedPart} onChange={(event)=>setSelectedPart(event.target.value)}><option value="">Choisir une référence</option>{data.dubaiParts.map((part)=><option value={part.id} key={part.id}>{part.name}</option>)}</select></Field><Field label="Quantité"><input className="input" type="number" inputMode="numeric" min="1" value={quantity} onChange={(event)=>setQuantity(Number(event.target.value))}/></Field></>:null}<Field label="Devise originale"><select className="select" value={actionCurrency} onChange={(event)=>setActionCurrency(event.target.value as Currency)}>{(["AED","EUR","FCFA","USD"] as Currency[]).map((item)=><option key={item}>{item}</option>)}</select></Field>{action==="expense"?<Field label="Référence liée"><select className="select" value={selectedPart} onChange={(event)=>setSelectedPart(event.target.value)}><option value="">Charge globale</option>{data.dubaiParts.map((part)=><option value={part.id} key={part.id}>{part.name}</option>)}</select></Field>:null}{action==="movement"?<><Field label="Type"><select className="select" value={movementType} onChange={(event)=>setMovementType(event.target.value as DubaiCashMovement["type"])}><option value="cash_in">Apport / Cash in</option><option value="cash_out">Décaissement / Cash out</option><option value="withdrawal">Retrait</option></select></Field><button className="card-flat spread" onClick={()=>setPlanned(!planned)}><span>Prévu à venir</span><span className={`status-dot ${planned?"active":""}`}>{planned?<Check size={14}/>:null}</span></button></>:null}</FormSection></div></Sheet>
  <ConfirmDialog open={Boolean(pendingDelete)} title="Confirmer la suppression ?" detail={`« ${pendingDelete?.label??"Cet élément"} » sera supprimé définitivement.`} onCancel={()=>setPendingDelete(undefined)} onConfirm={()=>{if(pendingDelete)remove(pendingDelete.kind==="part"?"dubaiParts":"dubaiCashMovements",pendingDelete.id);setPendingDelete(undefined);showToast({title:"Élément supprimé",tone:"success"});}}/>
 </main>;
}
